apiVersion: v1
kind: Service
metadata:
  name: test-eureka
  namespace: spring-application
  labels:
    app: test-eureka
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 31001
  selector:
    app: test-eureka

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: test-eureka
  namespace: spring-application
  labels:
    app: test-eureka
spec:
  serviceName: "test-eureka"
  replicas: 3
  selector:
    matchLabels:
      app: test-eureka
  template:
    metadata:
      namespace: spring-application
      labels:
        app: test-eureka
    spec:
      containers:
        - name: test-eureka
          image: octavianuszzw/test-eureka:master
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: EUREKA_INSTANCE_HOSTNAME
              value: ${MY_POD_NAME}.eureka
            - name: EUREKA_SERVER
              value: "http://test-eureka-0.test-eureka:8080/eureka/,http://test-eureka-1.test-eureka:8080/eureka/,http://test-eureka-2.test-eureka:8080/eureka/"
      imagePullSecrets:
        - name: mydockerhubregistrykey
  podManagementPolicy: "Parallel"